### ISSUE TITLE
Bullet speed

### ISSUE THREAD

**Issue by GrimPixel** [thelastflapjack/godot_open_target_shooter#9]
The speed of buttets is too slow, like toys. There could be some adjustments.

**Comment by teeeece** [comment]
The speed of the bullets from a weapon can be easily changed by changing the bullet_speed property of any given [Weapon](https://github.com/thelastflapjack/godot_open_target_shooter/blob/main/src/weapons/weapon.gd). I chose a value I was happy with at the time I made it, I don't see much point in changing the default. This is just meant to be a project for other people to build on top of. It isn't a game which I plan on tuneing small details of such as bullet speed.

**Comment by GrimPixel** [comment]
So you expect that players read the code and do themselves?

**Comment by teeeece** [comment]
Certainly not. Like I said in my previous comment, this project is mainly intended for other people to use as a base to build their own projects on top of. This project was mostly made for other developers to look at and use. So like I said, I'm not interested in putting effort into tuning specific values like bullet speed. I may adjust these small things when/if I port this project to Godot 4.x, but not before then.
